#! /usr/bin/env python3

#                                                                                      #
# wikipub: publish a generated page to the MapTasker GitHub wiki                        #
#                                                                                      #
# MIT License   Refer to https://opensource.org/license/mit                            #
"""Push one generated page to the MapTasker wiki.

The wiki is an ordinary git repository -- 'Map-Tasker.wiki.git', one markdown file per
page, the filename being the page name -- so publishing is a clone, a write and a push
rather than an API call.  There is no token to arrange: the credentials git already
uses for the Map-Tasker repository are the ones it uses here.

This started inside 'build_command_wiki.py' and moved out when a second generated page
needed the same treatment.  Both tools import it, so the wiki is only spoken to from
one place, and a page that is not generated by a tool is never touched.

The page is replaced wholesale, and nothing else in the clone is added, so a run can
only ever change the one page it was given.  When the generated page is identical to
the one already published, the run stops before committing and says so -- a wiki whose
history is full of empty "Update" commits is worse than one that is a day behind.

Publishing is a push to a public site, so it is never the default: a tool that imports
this offers it behind '--publish', and '--publish --dry-run' shows exactly what would
change without committing or pushing anything.
"""

from __future__ import annotations

import subprocess
import sys
import tempfile
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    import argparse

WIKI_URL = "https://github.com/mctinker/Map-Tasker/wiki"
WIKI_REPO = "https://github.com/mctinker/Map-Tasker.wiki.git"


def run_git(arguments: list[str], cwd: Path) -> subprocess.CompletedProcess:
    """Run one git command and hand back what it said.

    Args:
        arguments (list[str]): the arguments, without the leading 'git'.
        cwd (Path): the directory to run it in.

    Returns:
        subprocess.CompletedProcess: the finished command, its output captured.  The
            return code is not checked here; the caller decides what a failure means.
    """
    return subprocess.run(  # noqa: S603
        ["git", *arguments],  # noqa: S607
        cwd=cwd,
        capture_output=True,
        text=True,
        check=False,
    )


def add_publish_arguments(parser: argparse.ArgumentParser) -> None:
    """Give a tool the three flags publishing needs, so both tools spell them the same.

    Args:
        parser (argparse.ArgumentParser): the tool's own parser.
    """
    parser.add_argument("--publish", action="store_true", help="Push the page to the GitHub wiki.")
    parser.add_argument("--dry-run", action="store_true", help="With --publish: show the change, push nothing.")
    parser.add_argument("--wiki-repo", default=WIKI_REPO, help="Wiki git repository to publish to.")


def publish(page: Path, page_name: str, repo: str, dry_run: bool, tool: str = "") -> int:
    """Clone the wiki, replace the one page, and push it back.

    Only <page_name>.md is written; every other wiki page is left as it is.  With
    dry_run the clone and the write still happen so the diff can be shown, but nothing
    is committed or pushed.

    Args:
        page (Path): the generated page to publish.
        page_name (str): the wiki page it becomes -- 'Command-Reference' is published
            to <wiki>/Command-Reference and written as 'Command-Reference.md'.
        repo (str): the wiki git repository.
        dry_run (bool): show the change and stop.
        tool (str): the generator's name, for the commit message.  Defaults to the
            name of the script that called.

    Returns:
        int: 0 if the page was pushed, was already up to date, or was a dry run; 1 if
            the wiki could not be cloned or the push was refused.
    """
    tool = tool or Path(sys.argv[0]).name
    if not page.is_file():
        print(f"There is no page at {page} to publish.  Build it first.", file=sys.stderr)
        return 1

    with tempfile.TemporaryDirectory(prefix="maptasker-wiki-") as workspace:
        clone = Path(workspace) / "wiki"
        print(f"Cloning {repo} ...")
        result = run_git(["clone", "--depth", "1", repo, str(clone)], cwd=Path(workspace))
        if result.returncode != 0:
            print(result.stderr.strip(), file=sys.stderr)
            print(
                "Could not clone the wiki.  The wiki has to have at least one page already "
                "(create it once at " + WIKI_URL + "), and git needs push access to it.",
                file=sys.stderr,
            )
            return 1

        target = clone / f"{page_name}.md"
        target.write_text(page.read_text(encoding="utf-8"), encoding="utf-8")
        status = run_git(["status", "--porcelain"], cwd=clone)
        if not status.stdout.strip():
            print(f"'{page_name}' is already up to date -- nothing to push.")
            return 0

        diff = run_git(["diff", "--stat"], cwd=clone)
        print(diff.stdout.strip() or f"{page_name}.md is new.")
        if dry_run:
            print("--dry-run: not committing or pushing.")
            return 0

        message = f"Update {page_name} from {tool}"
        for arguments in (["add", target.name], ["commit", "-m", message], ["push"]):
            result = run_git(arguments, cwd=clone)
            if result.returncode != 0:
                print(result.stderr.strip() or result.stdout.strip(), file=sys.stderr)
                return 1
        print(f"Pushed '{page_name}' to {WIKI_URL}/{page_name}")
    return 0
